trigger:
- main

parameters:
- name: vmImage
  type: string
  default: ubuntu-latest
  values:
  - windows-latest
  - ubuntu-latest
  - macOS-latest
- name: 'buildConfiguration'
  type: string
  default: 'Debug'
  values:
  - 'Debug'
  - 'Release'
- name: 'SPXBuild_id'
  type: number
  default: 26811836
  values:
  - 0
  - 26811836

jobs:
- job: SPX_Yaml_Test_Pipeline
  pool:
    vmImage: ${{ parameters.vmImage }}

  steps:

    # -----------------------------------------------------------------------------
    # INSTALL DEPENDENCIES (GStreamer)
    # -----------------------------------------------------------------------------
    - script: |
        sudo apt install libgstreamer1.0-0 \
        gstreamer1.0-plugins-base \
        gstreamer1.0-plugins-good \
        gstreamer1.0-plugins-bad \
        gstreamer1.0-plugins-ugly
      displayName: INSTALL DEPENDENCIES (GStreamer)
      condition: not(eq('${{ parameters.vmImage }}', 'windows-latest'))

    # -----------------------------------------------------------------------------
    # GET SPX - NO SPXBuild_Id - Install via `dotnet tool install`
    # -----------------------------------------------------------------------------
    - task: DotNetCoreCLI@2      
      displayName: GET SPX - Installing via `dotnet tool install`
      inputs:
        command: 'custom'
        custom: 'tool'
        arguments: 'install --global Microsoft.CognitiveServices.Speech.CLI'
      condition: eq( ${{ parameters.SPXBuild_id }} , 0) # only if we have NO build_id

    # -----------------------------------------------------------------------------
    # GET SPX - Have SPXBuild_Id - Download artifact and unzip
    # -----------------------------------------------------------------------------
    - task: DownloadBuildArtifacts@0
      displayName: GET SPX - Have SPXBuild_id - DOWNLOAD
      inputs:
        buildType: specific
        project: 'e71f1362-9c7d-488b-99c7-3376db8d3302' # Skyman
        pipeline: 13649 # Azure-Samples.cognitive-services-speech-tools
        buildVersionToDownload: specific
        specificBuildWithTriggering: true
        buildId: ${{ parameters.SPXBuild_id }}
        downloadType: specific
        downloadPath: spxBuild
      condition: gt( ${{ parameters.SPXBuild_id }} , 0) # only if we have a build_id

    - task: ExtractFiles@1      
      displayName: GET SPX - Have SPXBuild_id - EXTRACT
      inputs:
        ${{ if eq(parameters.vmImage, 'windows-latest') }}:
          archiveFilePatterns: '**/spx-netcore31-win-x64.zip'
        ${{ else }}:
          archiveFilePatterns: '**/spx-netcore31-linux-x64.zip'
        destinationFolder: $(System.DefaultWorkingDirectory)/src/TestRunner/bin/${{ parameters.buildConfiguration }}/netcoreapp3.1/spx
        cleanDestinationFolder: false
      condition: gt( ${{ parameters.SPXBuild_id }} , 0) # only if we have a build_id

    - script: 'chmod u+x $(System.DefaultWorkingDirectory)/src/TestRunner/bin/${{ parameters.buildConfiguration }}/netcoreapp3.1/spx/spx'
      displayName: GET SPX - Have SPXBuild_id - CHMOD
      condition: and(gt( ${{ parameters.SPXBuild_id }} , 0), not(eq('${{ parameters.vmImage }}', 'windows-latest')))

    # -----------------------------------------------------------------------------
    # FIND and CONFIGURE SPX (LINUX)
    # -----------------------------------------------------------------------------
    - script: |
        echo '##vso[task.setvariable variable=path]$(PATH):$(System.DefaultWorkingDirectory)/src/TestRunner/bin/${{ parameters.buildConfiguration }}/netcoreapp3.1/spx:~/.dotnet/tools:'
      displayName: UPDATE PATH - Linux
      condition: not(eq('${{ parameters.vmImage }}', 'windows-latest'))

    - script: |
        echo ---
        set |grep -E -x --regexp="[a-zA-Z0-9_]+=.*"
        echo ---
        find
        find spx*
        find ~/.dotnet/tools/spx*
        echo ---
        echo cd src/TestRunner/bin/${{ parameters.buildConfiguration }}/netcoreapp3.1
        cd src/TestRunner/bin/${{ parameters.buildConfiguration }}/netcoreapp3.1
        echo ls
        ls
        echo ---
        echo PATH
        echo $(PATH)
        echo find spx*
        find spx*
        echo ---
        spx config local @region --set $(region)
        spx config local @key --set $(key)
        spx config local @
      displayName: FIND SPX and CONFIG - Linux
      condition: not(eq('${{ parameters.vmImage }}', 'windows-latest'))

    # -----------------------------------------------------------------------------
    # FIND and CONFIGURE SPX (WINDOWS)
    # -----------------------------------------------------------------------------
    - task: CmdLine@2
      displayName: UPDATE PATH - Windows
      inputs:
        script: |
          echo '##vso[task.setvariable variable=path]$(PATH);$(System.DefaultWorkingDirectory)\src\TestRunner\bin\${{ parameters.buildConfiguration }}\netcoreapp3.1\spx;'
      condition: eq('${{ parameters.vmImage }}', 'windows-latest')

    - task: CmdLine@2
      displayName: FIND SPX and CONFIG - Windows
      inputs:
        script: |
          echo ---
          set
          echo ---
          dir /s/b
          dir spx* /s/b
          echo ---
          echo cd src\TestRunner\bin\${{ parameters.buildConfiguration }}\netcoreapp3.1
          cd src\TestRunner\bin\${{ parameters.buildConfiguration }}\netcoreapp3.1
          echo dir *
          dir *
          echo ---
          dir /s/b
          dir spx* /s/b
          echo ---
          echo PATH
          set PATH
          echo where spx*
          where spx*
          echo ---
          spx.exe config local @region --set $(region)
          spx.exe config local @key --set $(key)
          spx.exe config local @
      condition: eq('${{ parameters.vmImage }}', 'windows-latest')

    # -----------------------------------------------------------------------------
    # Run the tests (this will also publish the results)
    # -----------------------------------------------------------------------------
    - task: DotNetCoreCLI@2
      displayName: RUN TESTS - Restore
      inputs:
        command: 'restore'
        arguments: '--configuration ${{ parameters.buildConfiguration }}'
        workingDirectory: $(System.DefaultWorkingDirectory)

    - task: DotNetCoreCLI@2      
      displayName: RUN TESTS - Build
      inputs:
        command: 'build'
        arguments: '--no-restore --configuration ${{ parameters.buildConfiguration }}'
        workingDirectory: $(System.DefaultWorkingDirectory)

    - task: DotNetCoreCLI@2      
      displayName: RUN TESTS - Test
      inputs:
        command: 'test'
        arguments: '--no-build --no-restore --configuration ${{ parameters.buildConfiguration }}'
        workingDirectory: $(System.DefaultWorkingDirectory)
